### ISSUE TITLE
-- Configuring incomplete, errors occurred!

### ISSUE THREAD

**Issue by jovelcjose** [fvannee/timestamp9#1]
Do i need to manually provide targets, i encountered following error

CMake Error at src/CMakeLists.txt:79 (install):
  install TARGETS given no LIBRARY DESTINATION for module target
  "timestamp9".

CMake Error at CMakeLists.txt:197 (get_parents):
  get_parents Macro invoked with incorrect arguments for macro named:
  get_parents

**Comment by fvannee** [comment]
I haven't seen that error before. Normally just calling `cmake` should work fine. Is it able to find the correct `pg_config`? What commands are you running exactly?
