### ISSUE TITLE
Subsecond timestamps without timezone are not accepted

### ISSUE THREAD

**Issue by oliora** [fvannee/timestamp9#5]
Subsecond timestamps without timezone are not accepted. `select '2019-09-19 08:30:05.123456789'::timestamp9;` gives an error:

```
ERROR:  invalid input format for timestamp9, required format y-m-d h:m:s.ns +tz "2019-09-19 08:30:05.123456789"
LINE 11: select '2019-09-19 08:30:05.123456789'::timestamp9;
                ^
SQL state: 22008
Character: 244
```

Both `timestamp` and `timestamptz` can parse the same string: `select '2019-09-19 08:30:05.123456789'::timestamp;` => `2019-09-19 08:30:05.123457`.

**Comment by fvannee** [comment]
I've added a commit that handles this more gracefully

**Comment by oliora** [comment]
Hi, thank you a lot for fixing this, but there are still issues with handling different formats of the string. Below are common formats that `timestamp` supports and `timestamp9` does not:

1. `'2022-07-21 12:33:03.123456Z'` and `'2022-07-21T12:33:03.123456Z'` (difference is only in date-time separator)
2. `'2022-07-21 12:33:03.123456789'` and `'2022-07-21T12:33:03.123456789'`
3. `'2022-07-21 12:33:03.123456789Z'` and `'2022-07-21T12:33:03.123456789Z'`

**Comment by fvannee** [comment]
Support for the first case should be easy to add, but I currently have no plans to implement (2) and (3). Up to microsecond, we can let Postgres logic handle the parsing, but when it starts involving nanoseconds currently we just have some simple parsing logic that requires the format `2022-07-21 12:33:03.123456789 +0200`

**Comment by oliora** [comment]
It would be great if you can fix the first case. This should cover my issue for now. 

I don’t have an immediate issue with other cases but I may hit them later. In such case, are you fine if I send a PR to fix them?

**Comment by fvannee** [comment]
Sure, happy to review PRs. First case should be fixed now in master.

**Comment by oliora** [comment]
Works great! Thank you for fixing it!
